baseURL = 'https://www.ecoauto.ir/'
locale = 'fa-IR'
defaultContentLanguage = 'fa'
title = 'اکواتو | قطعات خودروهای برقی'
enableGitInfo = false
paginate = 10

[markup.goldmark.renderer]
  unsafe = true

[params]
  description = 'فروشگاه تخصصی قطعات خودروهای برقی'
  rtl = true

[languages.fa]
  label = 'فارسی'
  contentDir = 'content'
  weight = 1

[outputs]
  home = ['HTML']
  section = ['HTML']
  page = ['HTML']
  taxonomy = ['HTML']
  term = ['HTML']

[taxonomies]
  category = 'categories'

[[menus.main]]
  name = 'صفحه اصلی'
  url = '/'
  weight = 1

[[menus.main]]
  name = 'محصولات'
  url = '/products/'
  weight = 2

[[menus.main]]
  name = 'دسته‌بندی‌ها'
  url = '/categories/'
  weight = 3

[[menus.main]]
  name = 'درباره ما'
  url = '/about/'
  weight = 4

[[menus.main]]
  name = 'تماس با ما'
  url = '/contact/'
  weight = 5

[[menus.main]]
  name = 'تامین‌کنندگان'
  url = '/vendors/'
  weight = 6

[[menus.main]]
  name = 'وبلاگ'
  url = '/blog/'
  weight = 7
